version: '3.9'
services:
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd2023
      - MONGO_INITDB_DATABASE=node-rest-api
    ports:
      - 27017:27017
    # volumes:
    #   - ./_data:/data/db